// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}

export { }
